name = "vite_cloudflare_example_hono"
compatibility_date = "2024-04-03"
workers_dev = true
main = "dist/index.js"

[[r2_buckets]]
binding = 'MY_BUCKET' # can be any valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAME>'

[env.development]

[[env.development.r2_buckets]]
binding = 'MY_BUCKET' # can be any valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAME>'
