// Generated by Wrangler on Wed Aug 21 2024 22:58:07 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env development`

interface Env {
	SESSION_SECRET: "super-secret";
	DO_SESSION: DurableObjectNamespace /* Session from ssr */;
}
