name = "vite_cloudflare_example_hono"
compatibility_date = "2024-04-03"
workers_dev = true

[env.production]

[[env.production.durable_objects.bindings]]
name = "DO_SESSION"
class_name = "SessionDurableObject"

[[env.production.migrations]]
tag = "v1"
new_classes = ["SessionDurableObject"]

[env.development]

[env.development.vars]
SESSION_SECRET = "super-secret"

[[env.development.durable_objects.bindings]]
name = "DO_SESSION"
class_name = "SessionDurableObject"
script_name = "ssr"

[[env.development.migrations]]
tag = "v1"
new_classes = ["SessionDurableObject"]
