name = "vite_cloudflare_example_hono"
compatibility_date = "2024-04-03"
workers_dev = true

[env.production]

[[durable_objects.bindings]]
name = "DO_SESSION"
class_name = "Session"

[[migrations]]
tag = "v1"
new_classes = ["Session"]

[env.development]

[[env.development.durable_objects.bindings]]
name = "DO_SESSION"
class_name = "Session"
script_name = "ssr"

[[env.development.migrations]]
tag = "v1"
new_classes = ["Session"]
