// Generated by Wrangler on Sun Aug 18 2024 11:48:55 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env development`

interface Env {
	DO_WEBSOCKET: DurableObjectNamespace /* WebSocketDurableObject from worker */;
}
